# Generated by Django 5.0 on 2025-12-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evidence_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
