# Generated by Django 5.0 on 2025-12-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_avatar_profile_location_alter_evidence_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
