# Generated by Django 5.0 on 2025-12-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_challan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_id', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('evidence_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], max_length=10)),
                ('evidence_file', models.FileField(upload_to='evidence/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
