# Generated by Django 5.0 on 2025-12-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_detectionboundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='memo_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='violation_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], max_length=10),
        ),
    ]
